application: sendfeedemail
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py
  
- url: /_ah/mail/.+ 
  script: /util/MailHandler.py
  login: admin