application: sendfeedemail
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
 
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /.*
  script: main.py
  
- url: /_ah/mail/.+ 
  script: /util/MailHandler.py
  login: admin
  
